# Generated by Django 2.0.7 on 2018-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shortcut', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesUnused',
            fields=[
                ('uniqueid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=10, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories_unused',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptNames',
            fields=[
                ('concept_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('concept_name', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'concept_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreAttributes',
            fields=[
                ('core_attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('core_attribute', models.TextField(blank=True, null=True)),
                ('is_literal_quotation', models.NullBooleanField()),
                ('page_num', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'core_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('complete_file_path', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='docs')),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_text', models.TextField(blank=True, null=True)),
                ('is_local_link', models.NullBooleanField()),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('paper_category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperConceptName',
            fields=[
                ('paper_concept_name_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_concept_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('paper_keyword_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paper_keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(blank=True, max_length=50, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('cite_command', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'papers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purposes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuperCategories',
            fields=[
                ('super_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'super_categories',
                'managed': False,
            },
        ),
    ]
